---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yourusername/public_html

    # Show current contents before cleaning
    - echo "Before cleaning public_html:"
    - ls -la $DEPLOYPATH

    # Delete all EXCEPT .htaccess and index.php
    - echo "Cleaning public_html except .htaccess and index.php"
    - find $DEPLOYPATH -mindepth 1 ! -name '.htaccess' ! -name 'index.php' -exec rm -rf {} +

    # Copy all repo files to public_html (excluding .git and .cpanel.yml)
    - echo "Copying files to public_html..."
    - rsync -av --exclude='.git' --exclude='.cpanel.yml' ./ $DEPLOYPATH/

    # Show result
    - echo "After deployment:"
    - ls -la $DEPLOYPATH
