---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pqqlulab/public_html
    - echo "Before cleaning public_html"
    - ls -la $DEPLOYPATH
    - echo "Cleaning public_html (except .htaccess)"
    - find $DEPLOYPATH -mindepth 1 ! -name '.htaccess' -delete
    - echo "After cleaning public_html"
    - ls -la $DEPLOYPATH
    - echo "Copying app to public_html"
    - ls -la
    - /bin/cp -R index.php start.php install.php 404.php router.php start.sh config src includes admin patient .htaccess composer.json vendor README.md README_RAILWAY.md Readme $DEPLOYPATH
    - find $DEPLOYPATH/logs -type f -delete
    - rm -rf $DEPLOYPATH/vendor
    - rm -rf $DEPLOYPATH/logs
    - rm -rf $DEPLOYPATH/uploads
    - rm -f $DEPLOYPATH/*.log
    - rm -f $DEPLOYPATH/*.xlsx
    - rm -f $DEPLOYPATH/config/database.sqlite
    - rm -f $DEPLOYPATH/*.sqlite
    - rm -f $DEPLOYPATH/.env*
    - rm -f $DEPLOYPATH/.DS_Store
    - rm -f $DEPLOYPATH/Thumbs.db
    - rm -f $DEPLOYPATH/test_db.php
    - echo "Deployment done"
