---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pqqlulab/public_html
    - export REPOPATH=/home/pqqlulab/repositories/tvmrewardsclone
    - echo "Before cleaning public_html"
    - ls -la $DEPLOYPATH
    - echo "Cleaning public_html (except .htaccess and wp-content)"
    - find $DEPLOYPATH -mindepth 1 ! -name '.htaccess' ! -name 'wp-content' -delete
    - echo "After cleaning public_html"
    - ls -la $DEPLOYPATH
    - echo "Copying app to public_html"
    - ls -la $REPOPATH
    - /bin/cp -R $REPOPATH/index.php $REPOPATH/404.php $REPOPATH/router.php $REPOPATH/install.php $REPOPATH/config $REPOPATH/src $REPOPATH/includes $REPOPATH/admin $REPOPATH/patient $REPOPATH/.htaccess $REPOPATH/composer.json $REPOPATH/README.md $REPOPATH/README_RAILWAY.md $REPOPATH/Readme $DEPLOYPATH
    - echo "Deployment done"
