version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: example
      DB_NAME: veteran
      SITE_URL: http://localhost:8080
      SESSION_NAME: veteran_session
      SESSION_LIFETIME: 3600
      PORT: 8080
      DEFAULT_POINTS_RATE: 100
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    command: ["./start.sh"]
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: veteran
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
volumes:
  db_data:
